(function() {var implementors = {};
implementors["ascii"] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/iter/traits/trait.Extend.html' title='core::iter::traits::Extend'>Extend</a>&lt;<a class='enum' href='ascii/enum.AsciiChar.html' title='ascii::AsciiChar'>AsciiChar</a>&gt; for <a class='struct' href='ascii/struct.AsciiString.html' title='ascii::AsciiString'>AsciiString</a>","impl&lt;'a&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/core/iter/traits/trait.Extend.html' title='core::iter::traits::Extend'>Extend</a>&lt;&amp;'a <a class='enum' href='ascii/enum.AsciiChar.html' title='ascii::AsciiChar'>AsciiChar</a>&gt; for <a class='struct' href='ascii/struct.AsciiString.html' title='ascii::AsciiString'>AsciiString</a>","impl&lt;'a&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/core/iter/traits/trait.Extend.html' title='core::iter::traits::Extend'>Extend</a>&lt;&amp;'a <a class='struct' href='ascii/struct.AsciiStr.html' title='ascii::AsciiStr'>AsciiStr</a>&gt; for <a class='struct' href='ascii/struct.AsciiString.html' title='ascii::AsciiString'>AsciiString</a>",];
implementors["encode_unicode"] = ["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/iter/traits/trait.Extend.html\" title=\"trait core::iter::traits::Extend\">Extend</a>&lt;<a class=\"struct\" href=\"encode_unicode/struct.Utf8Char.html\" title=\"struct encode_unicode::Utf8Char\">Utf8Char</a>&gt; for <a class=\"struct\" href=\"https://doc.rust-lang.org/nightly/collections/vec/struct.Vec.html\" title=\"struct collections::vec::Vec\">Vec</a>&lt;<a class=\"primitive\" href=\"https://doc.rust-lang.org/nightly/std/primitive.u8.html\">u8</a>&gt;","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/iter/traits/trait.Extend.html\" title=\"trait core::iter::traits::Extend\">Extend</a>&lt;<a class=\"struct\" href=\"encode_unicode/struct.Utf8Char.html\" title=\"struct encode_unicode::Utf8Char\">Utf8Char</a>&gt; for <a class=\"struct\" href=\"https://doc.rust-lang.org/nightly/collections/string/struct.String.html\" title=\"struct collections::string::String\">String</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/iter/traits/trait.Extend.html\" title=\"trait core::iter::traits::Extend\">Extend</a>&lt;<a class=\"struct\" href=\"encode_unicode/struct.Utf16Char.html\" title=\"struct encode_unicode::Utf16Char\">Utf16Char</a>&gt; for <a class=\"struct\" href=\"https://doc.rust-lang.org/nightly/collections/vec/struct.Vec.html\" title=\"struct collections::vec::Vec\">Vec</a>&lt;<a class=\"primitive\" href=\"https://doc.rust-lang.org/nightly/std/primitive.u16.html\">u16</a>&gt;",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
