(function() {var implementors = {};
implementors["ascii"] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/std/error/trait.Error.html' title='std::error::Error'>Error</a> for <a class='struct' href='ascii/struct.ToAsciiCharError.html' title='ascii::ToAsciiCharError'>ToAsciiCharError</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/std/error/trait.Error.html' title='std::error::Error'>Error</a> for <a class='struct' href='ascii/struct.AsAsciiStrError.html' title='ascii::AsAsciiStrError'>AsAsciiStrError</a>",];implementors["encode_unicode"] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/std/error/trait.Error.html' title='std::error::Error'>Error</a> for <a class='enum' href='encode_unicode/error/enum.InvalidCodepoint.html' title='encode_unicode::error::InvalidCodepoint'>InvalidCodepoint</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/std/error/trait.Error.html' title='std::error::Error'>Error</a> for <a class='enum' href='encode_unicode/error/enum.InvalidUtf16Tuple.html' title='encode_unicode::error::InvalidUtf16Tuple'>InvalidUtf16Tuple</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/std/error/trait.Error.html' title='std::error::Error'>Error</a> for <a class='enum' href='encode_unicode/error/enum.InvalidUtf16Slice.html' title='encode_unicode::error::InvalidUtf16Slice'>InvalidUtf16Slice</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/std/error/trait.Error.html' title='std::error::Error'>Error</a> for <a class='enum' href='encode_unicode/error/enum.FromStrError.html' title='encode_unicode::error::FromStrError'>FromStrError</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/std/error/trait.Error.html' title='std::error::Error'>Error</a> for <a class='enum' href='encode_unicode/error/enum.InvalidUtf8FirstByte.html' title='encode_unicode::error::InvalidUtf8FirstByte'>InvalidUtf8FirstByte</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/std/error/trait.Error.html' title='std::error::Error'>Error</a> for <a class='enum' href='encode_unicode/error/enum.InvalidUtf8.html' title='encode_unicode::error::InvalidUtf8'>InvalidUtf8</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/std/error/trait.Error.html' title='std::error::Error'>Error</a> for <a class='enum' href='encode_unicode/error/enum.InvalidUtf8Array.html' title='encode_unicode::error::InvalidUtf8Array'>InvalidUtf8Array</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/std/error/trait.Error.html' title='std::error::Error'>Error</a> for <a class='enum' href='encode_unicode/error/enum.InvalidUtf8Slice.html' title='encode_unicode::error::InvalidUtf8Slice'>InvalidUtf8Slice</a>",];
implementors["encode_unicode"] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/std/error/trait.Error.html' title='trait std::error::Error'>Error</a> for <a class='struct' href='encode_unicode/error/struct.InvalidUtf16FirstUnit.html' title='struct encode_unicode::error::InvalidUtf16FirstUnit'>InvalidUtf16FirstUnit</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/std/error/trait.Error.html' title='trait std::error::Error'>Error</a> for <a class='enum' href='encode_unicode/error/enum.InvalidCodepoint.html' title='enum encode_unicode::error::InvalidCodepoint'>InvalidCodepoint</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/std/error/trait.Error.html' title='trait std::error::Error'>Error</a> for <a class='enum' href='encode_unicode/error/enum.InvalidUtf16Tuple.html' title='enum encode_unicode::error::InvalidUtf16Tuple'>InvalidUtf16Tuple</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/std/error/trait.Error.html' title='trait std::error::Error'>Error</a> for <a class='enum' href='encode_unicode/error/enum.InvalidUtf16Slice.html' title='enum encode_unicode::error::InvalidUtf16Slice'>InvalidUtf16Slice</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/std/error/trait.Error.html' title='trait std::error::Error'>Error</a> for <a class='enum' href='encode_unicode/error/enum.FromStrError.html' title='enum encode_unicode::error::FromStrError'>FromStrError</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/std/error/trait.Error.html' title='trait std::error::Error'>Error</a> for <a class='enum' href='encode_unicode/error/enum.InvalidUtf8FirstByte.html' title='enum encode_unicode::error::InvalidUtf8FirstByte'>InvalidUtf8FirstByte</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/std/error/trait.Error.html' title='trait std::error::Error'>Error</a> for <a class='enum' href='encode_unicode/error/enum.InvalidUtf8.html' title='enum encode_unicode::error::InvalidUtf8'>InvalidUtf8</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/std/error/trait.Error.html' title='trait std::error::Error'>Error</a> for <a class='enum' href='encode_unicode/error/enum.InvalidUtf8Array.html' title='enum encode_unicode::error::InvalidUtf8Array'>InvalidUtf8Array</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/std/error/trait.Error.html' title='trait std::error::Error'>Error</a> for <a class='enum' href='encode_unicode/error/enum.InvalidUtf8Slice.html' title='enum encode_unicode::error::InvalidUtf8Slice'>InvalidUtf8Slice</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
